# Generated by Django 5.0 on 2024-01-26 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='user',
            new_name='profile_user',
        ),
    ]
